title: Wenhao Sun's Homepage
page-top-title: Wenhao Sun
top-section-bg-text: Mres Pattern Recognition And Intelligent Systems
home-subtitle: Wenhao Sun&ensp;|&ensp;孙文浩
copyright-text: '&copy; Wenhao Sun 2024-2025. All Rights Reserved.'
